// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaijiTapnU3JhjP_Asc6NcNpmWi1yIJIg',
    appId: '1:396792424952:web:3ab4368119ff4ab405ce0d',
    messagingSenderId: '396792424952',
    projectId: 'you-read-app-87d3d',
    authDomain: 'you-read-app-87d3d.firebaseapp.com',
    storageBucket: 'you-read-app-87d3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDggHnb5pOGh9Kc1NvkESjO1YyD37R71Eo',
    appId: '1:396792424952:android:8582aed716003cf405ce0d',
    messagingSenderId: '396792424952',
    projectId: 'you-read-app-87d3d',
    storageBucket: 'you-read-app-87d3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC7VUWwqr643MTz4xFai7v2nKacnhsq1E',
    appId: '1:396792424952:ios:769d1109a65478b705ce0d',
    messagingSenderId: '396792424952',
    projectId: 'you-read-app-87d3d',
    storageBucket: 'you-read-app-87d3d.appspot.com',
    androidClientId: '396792424952-b2u1p4umccd5bra3t5p2u9b24e38h5c6.apps.googleusercontent.com',
    iosClientId: '396792424952-s5gru64bsr07avoj1g8knbk8b3s8fg6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.youReadAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC7VUWwqr643MTz4xFai7v2nKacnhsq1E',
    appId: '1:396792424952:ios:769d1109a65478b705ce0d',
    messagingSenderId: '396792424952',
    projectId: 'you-read-app-87d3d',
    storageBucket: 'you-read-app-87d3d.appspot.com',
    androidClientId: '396792424952-b2u1p4umccd5bra3t5p2u9b24e38h5c6.apps.googleusercontent.com',
    iosClientId: '396792424952-s5gru64bsr07avoj1g8knbk8b3s8fg6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.youReadAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaijiTapnU3JhjP_Asc6NcNpmWi1yIJIg',
    appId: '1:396792424952:web:d3a54696944c60b305ce0d',
    messagingSenderId: '396792424952',
    projectId: 'you-read-app-87d3d',
    authDomain: 'you-read-app-87d3d.firebaseapp.com',
    storageBucket: 'you-read-app-87d3d.appspot.com',
  );
}
